class MyClass
  attr_reader :name
  attr_writer :name

  def initialize(name)
    @name = name
  end
end

obj = MyClass.new("John")
puts obj.name  # Output: John

obj.name = "Doe"  # This will invoke the writer method generated by attr_writer
puts obj.name  # Output: Doe

